# Generated by Django 5.1.7 on 2025-03-16 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_rename_price_products_unit_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='slug',
            field=models.SlugField(default='-'),
            preserve_default=False,
        ),
    ]
