# Generated by Django 5.1.7 on 2025-03-16 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_products_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='zip',
            field=models.CharField(default='', max_length=20, null=True),
        ),
    ]
