# Generated by Django 5.1.7 on 2025-03-16 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_customers_store_custo_last_na_e6a359_idx_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Customers',
            new_name='Customer',
        ),
        migrations.RemoveIndex(
            model_name='customer',
            name='store_custo_last_na_e6a359_idx',
        ),
        migrations.AlterModelTable(
            name='customer',
            table=None,
        ),
    ]
