# Generated by Django 5.1.7 on 2025-03-16 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_rename_featured_products_collection_featured_product_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='collection',
            old_name='featured_product_id',
            new_name='featured_product',
        ),
    ]
