# Generated by Django 5.1.7 on 2025-03-16 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_rename_featured_product_id_collection_featured_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='customers',
            new_name='customer',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='place_at',
            new_name='placed_at',
        ),
    ]
