# Generated by Django 5.1.7 on 2025-03-16 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_rename_customers_order_customer_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='products',
            new_name='product',
        ),
    ]
